# Generated by Django 5.1.7 on 2025-04-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_jobinterview_interviewer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobinterview',
            old_name='recruiter',
            new_name='hr_coordinator',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('department_manager', 'Department Manager'), ('hr_coordinator', 'HR Coordinator'), ('interviewer', 'Interviewer')], default='candidate', max_length=20),
        ),
    ]
