from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('skills/', views.manage_skills, name='manage_skills'),
    path('skills/delete/<int:skill_id>/', views.delete_skill, name='delete_skill'),
    path('education/', views.education_list, name='education_list'),
    path('education/add/', views.add_education, name='add_education'),
    path('education/<int:education_id>/edit/', views.edit_education, name='edit_education'),
    path('education/<int:education_id>/delete/', views.delete_education, name='delete_education'),
    path('jobs/', views.job_list, name='job_list'),
    path('jobs/<int:job_id>/', views.job_detail, name='job_detail'),
    path('jobs/create/', views.create_job, name='create_job'),
    path('jobs/<int:job_id>/delete/', views.delete_job, name='delete_job'),
    path('jobs/<int:job_id>/apply/', views.apply_for_job, name='apply_for_job'),
    path('applications/', views.application_list, name='application_list'),
    path('applications/<int:application_id>/', views.application_detail, name='application_detail'),
    path('applications/<int:application_id>/delete/', views.delete_application, name='delete_application'),
    path('applications/<int:application_id>/update-status/', views.update_application_status, name='update_application_status'),
    path('my-applications/', views.my_applications, name='my_applications'),
    path('my-applications/<int:application_id>/withdraw/', views.withdraw_application, name='withdraw_application'),
    path('my-applications/<int:application_id>/edit/', views.edit_application, name='edit_application'),
    path('my-applications/<int:application_id>/job-offer-response/', views.job_offer_response, name='job_offer_response'),
    path('interviews/', views.interview_list, name='interview_list'),
    path('interviews/schedule/<int:application_id>/', views.schedule_interview, name='schedule_interview'),
    path('interviews/<int:interview_id>/', views.interview_detail, name='interview_detail'),
    path('interviews/<int:interview_id>/update/', views.update_interview, name='update_interview'),
    path('interviews/<int:interview_id>/feedback/', views.interview_feedback, name='interview_feedback'),
    path('interviews/<int:interview_id>/interviewer-feedback/', views.interviewer_feedback, name='interviewer_feedback'),
    path('my-applications/<int:application_id>/interview/', views.candidate_view_interview, name='candidate_view_interview'),
    path('staff/', views.staff_list, name='staff_list'),
    path('staff/create/', views.create_staff, name='create_staff'),
    path('staff/<int:user_id>/edit/', views.edit_staff, name='edit_staff'),
    
    # Admin skills management
    path('skill-admin/', views.admin_skills, name='admin_skills'),
    path('skill-admin/add/', views.admin_add_skill, name='admin_add_skill'),
    path('skill-admin/<int:skill_id>/edit/', views.admin_edit_skill, name='admin_edit_skill'),
    path('skill-admin/<int:skill_id>/delete/', views.admin_delete_skill, name='admin_delete_skill'),
    path('skill-admin/normalize-categories/', views.normalize_skill_categories, name='normalize_skill_categories'),
]