# Generated by Django 5.1.7 on 2025-04-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_recruiter_jobinterview_hr_coordinator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboarding',
            name='application',
        ),
        migrations.RemoveField(
            model_name='onboarding',
            name='hr_coordinator',
        ),
        migrations.RemoveField(
            model_name='onboardingtask',
            name='onboarding',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='Onboarding',
        ),
        migrations.DeleteModel(
            name='OnboardingTask',
        ),
    ]
