# Generated by Django 5.1.7 on 2025-04-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_onboarding_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='job_postings', to='home.skill'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('hr_coordinator', 'HR Coordinator'), ('interviewer', 'Interviewer')], default='candidate', max_length=20),
        ),
    ]
